// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Im.Test.proto

#ifndef PROTOBUF_Im_2eTest_2eproto__INCLUDED
#define PROTOBUF_Im_2eTest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Im {
namespace Test {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Im_2eTest_2eproto();
void protobuf_AssignDesc_Im_2eTest_2eproto();
void protobuf_ShutdownFile_Im_2eTest_2eproto();

class Test;

// ===================================================================

class Test : public ::google::protobuf::Message {
 public:
  Test();
  virtual ~Test();

  Test(const Test& from);

  inline Test& operator=(const Test& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Test& default_instance();

  void Swap(Test* other);

  // implements Message ----------------------------------------------

  Test* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Test& from);
  void MergeFrom(const Test& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // repeated string name = 2;
  inline int name_size() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name(int index) const;
  inline ::std::string* mutable_name(int index);
  inline void set_name(int index, const ::std::string& value);
  inline void set_name(int index, const char* value);
  inline void set_name(int index, const char* value, size_t size);
  inline ::std::string* add_name();
  inline void add_name(const ::std::string& value);
  inline void add_name(const char* value);
  inline void add_name(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& name() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_name();

  // optional uint32 created_time = 3;
  inline bool has_created_time() const;
  inline void clear_created_time();
  static const int kCreatedTimeFieldNumber = 3;
  inline ::google::protobuf::uint32 created_time() const;
  inline void set_created_time(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Im.Test.Test)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_created_time();
  inline void clear_has_created_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> name_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::uint32 created_time_;
  friend void  protobuf_AddDesc_Im_2eTest_2eproto();
  friend void protobuf_AssignDesc_Im_2eTest_2eproto();
  friend void protobuf_ShutdownFile_Im_2eTest_2eproto();

  void InitAsDefaultInstance();
  static Test* default_instance_;
};
// ===================================================================


// ===================================================================

// Test

// required int32 id = 1;
inline bool Test::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Test::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Test::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Test::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Test::id() const {
  // @@protoc_insertion_point(field_get:Im.Test.Test.id)
  return id_;
}
inline void Test::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:Im.Test.Test.id)
}

// repeated string name = 2;
inline int Test::name_size() const {
  return name_.size();
}
inline void Test::clear_name() {
  name_.Clear();
}
inline const ::std::string& Test::name(int index) const {
  // @@protoc_insertion_point(field_get:Im.Test.Test.name)
  return name_.Get(index);
}
inline ::std::string* Test::mutable_name(int index) {
  // @@protoc_insertion_point(field_mutable:Im.Test.Test.name)
  return name_.Mutable(index);
}
inline void Test::set_name(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Im.Test.Test.name)
  name_.Mutable(index)->assign(value);
}
inline void Test::set_name(int index, const char* value) {
  name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Im.Test.Test.name)
}
inline void Test::set_name(int index, const char* value, size_t size) {
  name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Im.Test.Test.name)
}
inline ::std::string* Test::add_name() {
  return name_.Add();
}
inline void Test::add_name(const ::std::string& value) {
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Im.Test.Test.name)
}
inline void Test::add_name(const char* value) {
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Im.Test.Test.name)
}
inline void Test::add_name(const char* value, size_t size) {
  name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Im.Test.Test.name)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Test::name() const {
  // @@protoc_insertion_point(field_list:Im.Test.Test.name)
  return name_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Test::mutable_name() {
  // @@protoc_insertion_point(field_mutable_list:Im.Test.Test.name)
  return &name_;
}

// optional uint32 created_time = 3;
inline bool Test::has_created_time() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Test::set_has_created_time() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Test::clear_has_created_time() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Test::clear_created_time() {
  created_time_ = 0u;
  clear_has_created_time();
}
inline ::google::protobuf::uint32 Test::created_time() const {
  // @@protoc_insertion_point(field_get:Im.Test.Test.created_time)
  return created_time_;
}
inline void Test::set_created_time(::google::protobuf::uint32 value) {
  set_has_created_time();
  created_time_ = value;
  // @@protoc_insertion_point(field_set:Im.Test.Test.created_time)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Test
}  // namespace Im

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Im_2eTest_2eproto__INCLUDED
